# M. Kaan Tasbas | mktasbas@gmail.com

# Modified from https://github.com/shadow-robot/build-servers-check/blob/kinetic-devel/.travis.yml
# ROS Continuous Integration Wiki: http://wiki.ros.org/CIs

sudo: required

language: cpp

services:
  - docker

env:
  global:
    - toolset_branch: master
    - server_type: travis
    - ros_release_name: kinetic
    - ubuntu_version_name: xenial
    - used_modules: check_cache,check_build
    - remote_shell_script: 'https://raw.githubusercontent.com/shadow-robot/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh'

script:
  - curl -s "$( echo "$remote_shell_script" | sed 's/#/%23/g' )" | bash -x /dev/stdin "$toolset_branch" $server_type $used_modules
