set(_CATKIN_CURRENT_PACKAGE "cv_pipeline")
set(cv_pipeline_VERSION "0.0.0")
set(cv_pipeline_MAINTAINER "M. Kaan Tasbas <mktasbas@gmail.com>")
set(cv_pipeline_PACKAGE_FORMAT "2")
set(cv_pipeline_BUILD_DEPENDS "camera_calibration" "cv_bridge" "cv_camera" "image_transport" "image_view" "nodelet" "opencv3" "roscpp" "std_msgs" "stereo_image_proc")
set(cv_pipeline_BUILD_EXPORT_DEPENDS "camera_calibration" "cv_bridge" "cv_camera" "image_transport" "image_view" "nodelet" "opencv3" "roscpp" "std_msgs" "stereo_image_proc")
set(cv_pipeline_BUILDTOOL_DEPENDS "catkin")
set(cv_pipeline_BUILDTOOL_EXPORT_DEPENDS )
set(cv_pipeline_EXEC_DEPENDS "camera_calibration" "cv_bridge" "cv_camera" "image_transport" "image_view" "nodelet" "opencv3" "roscpp" "std_msgs" "stereo_image_proc")
set(cv_pipeline_RUN_DEPENDS "camera_calibration" "cv_bridge" "cv_camera" "image_transport" "image_view" "nodelet" "opencv3" "roscpp" "std_msgs" "stereo_image_proc")
set(cv_pipeline_TEST_DEPENDS )
set(cv_pipeline_DOC_DEPENDS )
set(cv_pipeline_URL_WEBSITE "")
set(cv_pipeline_URL_BUGTRACKER "")
set(cv_pipeline_URL_REPOSITORY "")
set(cv_pipeline_DEPRECATED "")